//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFPE.FeatureModelDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "fm";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FeatureModelDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UFPE";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FeatureModelDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FeatureModelDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFeatureModelDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string FeatureModelDSLPackageId = "abe2bc90-2b20-4ee8-9922-9ebbd51bd3b3";
		
		// Editor factory identifier
		public const string FeatureModelDSLEditorFactoryId = "462dce01-ed90-4d48-876f-a2101b91e3bf";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FeatureModelDSLModelExplorerToolWindowId = "2491ec2e-9b53-41dc-bc99-21a4637ce006";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UFPE.FeatureModelDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FeatureModelDSLCommandSetId = "1331d3f6-ad13-47d2-ab13-3763b1339b86";
	}
}