
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using VSTextTemplatingHost = global::Microsoft.VisualStudio.TextTemplating.VSHost;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace UFPE.FeatureModelDSL
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\10.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(FeatureModelDSLExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(FeatureModelDSLExplorerToolWindow), Constants.FeatureModelDSLEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@FeatureModelDSLToolboxTab;UFPE.FeatureModelDSL.Dsl.dll", "UFPE.FeatureModelDSL.FeatureModelDSLToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UFPE.FeatureModelDSL.FeatureModelDSLToolboxTab",
					"@FeatureToolboxItem;UFPE.FeatureModelDSL.Dsl.dll", 
					"UFPE.FeatureModelDSL.FeatureToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"", 
					"@FeatureToolboxBitmap;UFPE.FeatureModelDSL.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("UFPE.FeatureModelDSL.FeatureModelDSLToolboxTab",
					"@ConnectToolboxItem;UFPE.FeatureModelDSL.Dsl.dll", 
					"UFPE.FeatureModelDSL.ConnectToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"", 
					"@ConnectToolboxBitmap;UFPE.FeatureModelDSL.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("UFPE.FeatureModelDSL.FeatureModelDSLToolboxTab",
					"@AlternativeToolboxItem;UFPE.FeatureModelDSL.Dsl.dll", 
					"UFPE.FeatureModelDSL.AlternativeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Alternative", 
					"@AlternativeToolboxBitmap;UFPE.FeatureModelDSL.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("UFPE.FeatureModelDSL.FeatureModelDSLToolboxTab",
					"@ConstraintToolboxItem;UFPE.FeatureModelDSL.Dsl.dll", 
					"UFPE.FeatureModelDSL.ConstraintToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Constraint", 
					"@ConstraintToolboxBitmap;UFPE.FeatureModelDSL.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(FeatureModelDSLEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(FeatureModelDSLEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"FeatureModelDSL", typeof(FeatureModelDSLEditorFactory))]
	internal abstract partial class FeatureModelDSLPackageBase : DslShell::ModelingPackage
	{
		protected global::UFPE.FeatureModelDSL.FeatureModelDSLToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new FeatureModelDSLEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UFPE.FeatureModelDSL.FeatureModelDSLToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			FeatureModelDSLCommandSet commandSet = new FeatureModelDSLCommandSet(this);
			commandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(FeatureModelDSLExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UFPE.FeatureModelDSL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	/// <remarks>
	/// A package load key is required to allow this package to load when the Visual Studio SDK is not installed.
	/// Package load keys may be obtained from http://msdn.microsoft.com/vstudio/extend.
	/// Consult the Visual Studio SDK documentation for more information.
	/// [VSShell::ProvideLoadKey("Standard", Constants.ProductVersion, Constants.ProductName, Constants.CompanyName, 1)]
	/// </remarks>
	[VSShell::ProvideLoadKey("Standard", Constants.ProductVersion, Constants.ProductName, Constants.CompanyName, 105)]
	[VSShell::ProvideMenuResource("1000.ctmenu", 4)]
	[VSShell::ProvideToolboxItems(1)]
	[VSTextTemplatingHost::ProvideDirectiveProcessor(typeof(global::UFPE.FeatureModelDSL.FeatureModelDSLDirectiveProcessor), global::UFPE.FeatureModelDSL.FeatureModelDSLDirectiveProcessor.FeatureModelDSLDirectiveProcessorName, "A directive processor that provides access to FeatureModelDSL files")]
	[global::System.Runtime.InteropServices.Guid(Constants.FeatureModelDSLPackageId)]
	[VSTextTemplatingHost:: ProvideIncludeFolder(".tt", 1, "TextTemplates")]
	internal sealed partial class FeatureModelDSLPackage : FeatureModelDSLPackageBase
	{
	}
}